[package]
name = "mcmappings-sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {"version" = "0.11.0", features = ["default"]}
rusqlite = {"version" = "0.38.0", features = ["bundled"]}
proguard = "5.9.0"
thiserror = "2.0.18"
log = "0.4.29"
env_logger = "0.11.9"